Repository Salabim-mb/Usamodzielnieni, pull requests merged in 2020-05, with the labels that each got.

#129 Chats
  front-end/src/Views/Chats/Chats.jsx
  front-end/src/Views/Chats/Chats.test.js
  front-end/src/Views/Chats/__snapshots__/Chats.test.js.snap
  front-end/src/Views/Chats/components/ChatInfo/ChatInfo.jsx
  front-end/src/Views/Chats/components/ChatInfo/ChatInfo.test.js
  front-end/src/Views/Chats/components/ChatInfo/__snapshots__/ChatInfo.test.js.snap
  front-end/src/Views/Chats/components/index.js
  front-end/src/Views/Chats/index.js
  front-end/src/Views/UserProfilePage/components/UserBasicInfo/UserBasicInfo.jsx
  front-end/src/Views/index.js
  front-end/src/components/UserPicture/UserPicture.jsx
  front-end/src/components/UserPicture/UserPicture.test.js
  front-end/src/components/UserPicture/__snapshots__/UserPicture.test.js.snap
  front-end/src/components/index.js
  front-end/src/config/api.js
  front-end/src/constants/menuPositions.js
  front-end/src/constants/paths.js
  front-end/src/constants/routes.js
  front-end/src/sass/components/_userPicture.scss
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_chats.scss
Labels: priority

#134 Lista wiadomości w chacie
  front-end/src/Views/MessagesList/MessagesList.jsx
  front-end/src/Views/MessagesList/MessagesList.test.js
  front-end/src/Views/MessagesList/__snapshots__/MessagesList.test.js.snap
  front-end/src/Views/MessagesList/components/MessageItem/MessageItem.jsx
  front-end/src/Views/MessagesList/components/MessageItem/MessageItem.test.js
  front-end/src/Views/MessagesList/components/MessageItem/__snapshots__/MessageItem.test.js.snap
  front-end/src/Views/MessagesList/components/MessageItem/index.js
  front-end/src/Views/MessagesList/components/index.js
  front-end/src/Views/MessagesList/index.js
  front-end/src/Views/index.js
  front-end/src/config/api.js
  front-end/src/constants/paths.js
  front-end/src/constants/routes.js
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_messagesList.scss
Labels: priority

#131 Cv feedback
  front-end/.gitignore
  front-end/package-lock.json
  front-end/package.json
  front-end/src/Views/CVApprovalPage/components/CVPosition.js
  front-end/src/Views/CVCorrection/CVCorrection.jsx
  front-end/src/Views/CVCorrection/CVCorrection.test.js
  front-end/src/Views/CVCorrection/__snapshots__/CVCorrection.test.js.snap
  front-end/src/Views/CVCorrection/_components/CVRender/CVRender.jsx
  front-end/src/Views/CVCorrection/_components/CVRender/CVRender.test.js
  front-end/src/Views/CVCorrection/_components/CVRender/__snapshots__/CVRender.test.js.snap
  front-end/src/Views/CVCorrection/_components/CVRender/index.js
  front-end/src/Views/CVCorrection/_components/CorrectionForm/CorrectionForm.jsx
  front-end/src/Views/CVCorrection/_components/CorrectionForm/CorrectionForm.test.js
  front-end/src/Views/CVCorrection/_components/CorrectionForm/__snapshots__/CorrectionForm.test.js.snap
  front-end/src/Views/CVCorrection/_components/CorrectionForm/index.js
  front-end/src/Views/CVCorrection/_components/PaginationCV/PaginationCV.jsx
  front-end/src/Views/CVCorrection/_components/PaginationCV/PaginationCV.test.js
  front-end/src/Views/CVCorrection/_components/PaginationCV/__snapshots__/PaginationCV.test.js.snap
  front-end/src/Views/CVCorrection/_components/PaginationCV/index.js
  front-end/src/Views/CVCorrection/_components/index.js
  front-end/src/Views/CVCorrection/functions/index.js
  front-end/src/Views/CVCorrection/index.js
  front-end/src/Views/index.js
  front-end/src/components/FormGroup/FormGroup.jsx
  front-end/src/constants/paths.js
  front-end/src/constants/routes.js
  front-end/src/sass/components/_formGroup.scss
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_CVCorrection.scss
  front-end/src/sass/pages/_offerForm.scss
Labels: priority

#143 Make blogs public again
  front-end/src/Views/BlogPage/BlogPage.jsx
  front-end/src/Views/BlogPage/BlogPage.test.js
  front-end/src/Views/BlogPage/__snapshots__/BlogPage.test.js.snap
  front-end/src/Views/BlogPage/components/Filter/Filter.jsx
  front-end/src/Views/BlogPage/components/SmallBlogPost/SmallBlogPost.jsx
  front-end/src/Views/BlogPage/functions/fetchData.js
  front-end/src/Views/BlogPost/BlogPost.jsx
  front-end/src/Views/BlogPost/BlogPost.test.js
  front-end/src/Views/BlogPost/__snapshots__/BlogPost.test.js.snap
  front-end/src/Views/BlogPost/_components/BlogContent/BlogContent.jsx
  front-end/src/Views/BlogPost/_components/BlogContent/__snapshots__/blogContent.test.js.snap
  front-end/src/Views/BlogPost/_components/BlogContent/blogContent.test.js
  front-end/src/Views/BlogPost/_components/CommentForm/CommentForm.jsx
  front-end/src/Views/BlogPost/_components/CommentForm/CommentForm.test.js
  front-end/src/Views/BlogPost/_components/CommentForm/__snapshots__/CommentForm.test.js.snap
  front-end/src/Views/BlogPost/_components/CommentItem/CommentItem.jsx
  front-end/src/Views/BlogPost/_components/CommentItem/CommentItem.test.js
  front-end/src/Views/BlogPost/_components/CommentItem/__snapshots__/CommentItem.test.js.snap
  front-end/src/Views/BlogPost/_components/CommentsList/__snapshots__/CommentsList.test.js.snap
  front-end/src/Views/BlogPost/functions/apiCalls.js
  front-end/src/constants/menuPositions.js
  front-end/src/constants/routes.js
Labels: priority

#156 Delete account
  front-end/jsconfig.json
  front-end/src/Views/UserProfilePage/UserProfilePage.jsx
  front-end/src/Views/UserProfilePage/__snapshots__/UserProfilePage.test.js.snap
  front-end/src/Views/UserProfilePage/components/AdminApproveUserButton/AdminApproveUserButton.js
  front-end/src/Views/UserProfilePage/components/AdminOfferApprovalButton/AdminOfferApprovalButton.js
  front-end/src/Views/UserProfilePage/components/ButtonsContainer/ButtonsContainer.jsx
  front-end/src/Views/UserProfilePage/components/CVApprovalButton/CVApprovalButton.jsx
  front-end/src/Views/UserProfilePage/components/DeleteAccountButton/DeleteAccountButton.jsx
  front-end/src/Views/UserProfilePage/components/DeleteAccountButton/DeleteAccountButton.test.js
  front-end/src/Views/UserProfilePage/components/DeleteAccountButton/__snapshots__/DeleteAccountButton.test.js.snap
  front-end/src/Views/UserProfilePage/components/UserListButton/UserListButton.jsx
  front-end/src/Views/UserProfilePage/components/index.js
  front-end/src/sass/pages/_userProfilePage.scss
Labels: priority

#160 Specialist account
  front-end/src/constants/userTypes.js
  front-end/src/root/_components/PrivateRoute/PrivateRoute.jsx
  front-end/src/root/_components/PrivateRoute/PrivateRoute.test.js
Labels: priority

#102 added pay details to OfferFrom
  front-end/src/Views/JobOfferDetails/JobOfferDetails.jsx
  front-end/src/Views/JobOfferDetails/JobOfferDetails.test.js
  front-end/src/Views/JobOfferDetails/__snapshots__/JobOfferDetails.test.js.snap
  front-end/src/Views/JobOffersPage/_components/Filter/Filter.jsx
  front-end/src/Views/OfferApprovalPage/OfferApprovalPage.test.jsx
  front-end/src/Views/OfferApprovalPage/__snapshots__/OfferApprovalPage.test.jsx.snap
  front-end/src/Views/OfferApprovalPage/components/OfferPosition.js
  front-end/src/Views/OfferForm/OfferForm.jsx
  front-end/src/Views/OfferForm/OfferForm.test.js
  front-end/src/Views/OfferForm/__snapshots__/OfferForm.test.js.snap
  front-end/src/components/FormGroup/FormGroup.jsx
Labels: priority

#159 Post media
  front-end/public/index.html
  front-end/src/Views/BlogPage/BlogPage.jsx
  front-end/src/Views/BlogPost/__snapshots__/BlogPost.test.js.snap
  front-end/src/Views/BlogPost/_components/BlogContent/BlogContent.jsx
  front-end/src/Views/BlogPost/_components/BlogContent/__snapshots__/blogContent.test.js.snap
  front-end/src/Views/BlogPostForm/BlogPostForm.test.js
  front-end/src/Views/BlogPostForm/BlogpostForm.jsx
  front-end/src/Views/BlogPostForm/__snapshots__/BlogPostForm.test.js.snap
  front-end/src/Views/BlogPostForm/components/ButtonList.js
  front-end/src/Views/BlogPostForm/components/ButtonList.test.js
  front-end/src/Views/BlogPostForm/components/EditorForm.js
  front-end/src/Views/BlogPostForm/components/EditorForm.test.js
  front-end/src/Views/BlogPostForm/components/SelectionRow.test.js
  front-end/src/Views/BlogPostForm/components/__snapshots__/ButtonList.test.js.snap
  front-end/src/Views/BlogPostForm/components/__snapshots__/EditorForm.test.js.snap
  front-end/src/Views/BlogPostForm/components/__snapshots__/SelectionRow.test.js.snap
  front-end/src/Views/BlogPostForm/functions/apiCalls.js
  front-end/src/Views/BlogPostForm/functions/editorConfig.js
Labels: question

#136 Cv load
  front-end/src/Views/CVEditorPage/CVDataLoading.test.js
  front-end/src/Views/CVEditorPage/CVEditorPage.jsx
  front-end/src/Views/CVEditorPage/CVEditorPage.test.js
  front-end/src/Views/CVEditorPage/__snapshots__/CVEditorPage.test.js.snap
  front-end/src/Views/CVEditorPage/components/ActionWithDate/ActionWithDate.jsx
  front-end/src/Views/CVEditorPage/components/ActionWithDate/ActionWithDate.test.js
  front-end/src/Views/CVEditorPage/components/ActionWithDate/__snapshots__/ActionWithDate.test.js.snap
  front-end/src/Views/CVEditorPage/components/CVEditorTab/CVEditorTab.jsx
  front-end/src/Views/CVEditorPage/components/CVEditorTab/CVEditorTab.test.js
  front-end/src/Views/CVEditorPage/components/CVEditorTab/__snapshots__/CVEditorTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/EducationTab/EducationTab.jsx
  front-end/src/Views/CVEditorPage/components/EducationTab/__snapshots__/EducationTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/ItemsList/ItemsList.jsx
  front-end/src/Views/CVEditorPage/components/ItemsList/ItemsList.test.js
  front-end/src/Views/CVEditorPage/components/LanguagesTab/LanguagesTab.jsx
  front-end/src/Views/CVEditorPage/components/LanguagesTab/__snapshots__/LanguagesTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/PersonalDataTab/PersonalDataTab.jsx
  front-end/src/Views/CVEditorPage/components/PersonalDataTab/PersonalDataTab.test.js
  front-end/src/Views/CVEditorPage/components/PersonalDataTab/__snapshots__/PersonalDataTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/PhotoTab/PhotoTab.jsx
  front-end/src/Views/CVEditorPage/components/PhotoTab/PhotoTab.test.js
  front-end/src/Views/CVEditorPage/components/PhotoTab/__snapshots__/PhotoTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/SkillsTab/SkillsTab.jsx
  front-end/src/Views/CVEditorPage/components/SkillsTab/__snapshots__/SkillsTab.test.js.snap
  front-end/src/Views/CVEditorPage/components/WorkExperienceTab/__snapshots__/WorkExperienceTab.test.js.snap
  front-end/src/Views/CVEditorPage/functions/__snapshots__/mapData.test.js.snap
  front-end/src/Views/CVEditorPage/functions/mapData.js
  front-end/src/Views/CVEditorPage/functions/mapData.test.js
  front-end/src/Views/CVEditorPage/functions/other.js
  front-end/src/Views/CVEditorPage/functions/other.test.js
  front-end/src/Views/MyCVsPage/components/cvSection.js
Labels: priority

#169 Comment delete timeout
  front-end/src/Views/BlogPost/_components/CommentItem/CommentItem.jsx
  front-end/src/Views/BlogPost/_components/CommentItem/__snapshots__/CommentItem.test.js.snap
  front-end/src/utils/renderWithTimeout/__snapshots__/renderWithTimeout.test.js.snap
  front-end/src/utils/renderWithTimeout/renderWithTimeout.js
  front-end/src/utils/renderWithTimeout/renderWithTimeout.test.js
Labels: priority

#130 Kroki usamodzielnienia
  front-end/src/Views/Steps/Steps.jsx
  front-end/src/Views/Steps/Steps.test.js
  front-end/src/Views/Steps/__snapshots__/Steps.test.js.snap
  front-end/src/Views/Steps/components/Bullet/Bullet.jsx
  front-end/src/Views/Steps/components/Bullet/Bullet.test.js
  front-end/src/Views/Steps/components/Bullet/__snapshots__/Bullet.test.js.snap
  front-end/src/Views/Steps/components/ProgressBar/ProgressBar.jsx
  front-end/src/Views/Steps/components/ProgressBar/ProgressBar.test.js
  front-end/src/Views/Steps/components/ProgressBar/__snapshots__/ProgressBar.test.js.snap
  front-end/src/Views/Steps/components/ProgressBarFragment/ProgressBarFragment.jsx
  front-end/src/Views/Steps/components/ProgressBarFragment/ProgressBarFragment.test.js
  front-end/src/Views/Steps/components/ProgressBarFragment/__snapshots__/ProgressBarFragment.test.js.snap
  front-end/src/Views/Steps/components/StepInfo/StepInfo.jsx
  front-end/src/Views/Steps/components/StepInfo/StepInfo.test.js
  front-end/src/Views/Steps/components/StepInfo/__snapshots__/StepInfo.test.js.snap
  front-end/src/Views/Steps/components/index.js
  front-end/src/Views/Steps/index.js
  front-end/src/Views/index.js
  front-end/src/config/api.js
  front-end/src/constants/menuPositions.js
  front-end/src/constants/paths.js
  front-end/src/constants/routes.js
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_steps.scss
Labels: priority

#164 Block user
  front-end/src/Views/Steps/components/ProgressBar/ProgressBar.jsx
  front-end/src/Views/Steps/components/ProgressBarFragment/ProgressBarFragment.jsx
  front-end/src/Views/Steps/components/StepCard/StepCard.jsx
  front-end/src/Views/Steps/components/StepCard/StepCard.test.js
  front-end/src/Views/UserList/UserList.jsx
  front-end/src/Views/UserList/UserList.test.js
  front-end/src/Views/UserList/__snapshots__/UserList.test.js.snap
  front-end/src/Views/UserList/components/BlockAccountButton.jsx
  front-end/src/Views/UserList/components/BlockAccountButton.test.js
  front-end/src/Views/UserList/components/ButtonsContainer.jsx
  front-end/src/Views/UserList/components/ButtonsContainer.test.js
  front-end/src/Views/UserList/components/DeleteAccountButton.jsx
  front-end/src/Views/UserList/components/DeleteAccountButton.test.js
  front-end/src/Views/UserList/components/UnblockAccountButton.jsx
  front-end/src/Views/UserList/components/UnblockAccountButton.test.js
  front-end/src/Views/UserList/components/UserInfo.jsx
  front-end/src/Views/UserList/components/UserInfo.test.js
  front-end/src/Views/UserList/components/__snapshots__/BlockAccountButton.test.js.snap
  front-end/src/Views/UserList/components/__snapshots__/ButtonsContainer.test.js.snap
  front-end/src/Views/UserList/components/__snapshots__/DeleteAccountButton.test.js.snap
  front-end/src/Views/UserList/components/__snapshots__/UnblockAccountButton.test.js.snap
  front-end/src/Views/UserList/components/__snapshots__/UserInfo.test.js.snap
  front-end/src/components/Player/Player.jsx
  front-end/src/components/Player/index.js
  front-end/src/sass/pages/_userProfilePage.scss
Labels: priority

#180 fixed rednering
  front-end/src/Views/CVApprovalPage/CVApprovalPage.jsx
  front-end/src/Views/CVApprovalPage/CVApprovalPage.test.js
  front-end/src/Views/CVApprovalPage/_components/CVPosition.test.js
  front-end/src/Views/MyCVsPage/MyCVsPage.jsx
  front-end/src/Views/MyCVsPage/MyCVsPage.test.js
  front-end/src/sass/main.scss
Labels: priority

#185 fixed applying to job offer select
  front-end/src/Views/JobOfferDetails/_components/AddCvForm/AddCvForm.jsx
  front-end/src/Views/JobOfferDetails/_components/AddCvForm/AddCvForm.test.js
Labels: priority

#149 Staff - zmiana danych na prośbę użytkownika
  front-end/src/Views/ChangeData/ChangeData.jsx
  front-end/src/Views/ChangeData/ChangeData.test.js
  front-end/src/Views/ChangeData/__snapshots__/ChangeData.test.js.snap
  front-end/src/Views/ChangeData/components/CompanyForm/CompanyForm.jsx
  front-end/src/Views/ChangeData/components/CompanyForm/CompanyForm.test.js
  front-end/src/Views/ChangeData/components/CompanyForm/__snapshots__/CompanyForm.test.js.snap
  front-end/src/Views/ChangeData/components/CompanyForm/index.js
  front-end/src/Views/ChangeData/components/FacilityForm/FacilityForm.jsx
  front-end/src/Views/ChangeData/components/FacilityForm/FacilityForm.test.js
  front-end/src/Views/ChangeData/components/FacilityForm/__snapshots__/FacilityForm.test.js.snap
  front-end/src/Views/ChangeData/components/FacilityForm/index.js
  front-end/src/Views/ChangeData/components/index.js
  front-end/src/Views/ChangeData/functions/changeData.js
  front-end/src/Views/ChangeData/index.js
  front-end/src/Views/UserList/components/ButtonsContainer.jsx
  front-end/src/Views/UserProfilePage/components/AdminApproveUserButton/AdminApproveUserButton.js
  front-end/src/Views/UserProfilePage/components/AdminOfferApprovalButton/AdminOfferApprovalButton.js
  front-end/src/Views/UserProfilePage/components/AdminRegisterButton/AdminRegisterButton.jsx
  front-end/src/Views/UserProfilePage/components/ButtonsContainer/ButtonsContainer.jsx
  front-end/src/Views/UserProfilePage/components/CVApprovalButton/CVApprovalButton.jsx
  front-end/src/Views/UserProfilePage/components/DeleteAccountButton/DeleteAccountButton.jsx
  front-end/src/Views/UserProfilePage/components/EmployerMyOffersButton/EmployerMyOffersButton.js
  front-end/src/Views/UserProfilePage/components/UserListButton/UserListButton.jsx
  front-end/src/Views/index.js
  front-end/src/components/FormGroup/FormGroup.jsx
  front-end/src/constants/paths.js
  front-end/src/constants/routes.js
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_changeData.scss
Labels: priority

#151 Okienka z filmami + przycisk do edytowania
  front-end/src/Views/CVEditorPage/CVEditorPage.jsx
  front-end/src/Views/CVEditorPage/components/CVEditorTab/CVEditorTab.jsx
  front-end/src/Views/CVEditorPage/components/EducationTab/EducationTab.jsx
  front-end/src/Views/CVEditorPage/components/LanguagesTab/LanguagesTab.jsx
  front-end/src/Views/CVEditorPage/components/PersonalDataTab/PersonalDataTab.jsx
  front-end/src/Views/CVEditorPage/components/PhotoTab/PhotoTab.jsx
  front-end/src/Views/CVEditorPage/components/SkillsTab/SkillsTab.jsx
  front-end/src/Views/CVEditorPage/components/WorkExperienceTab/WorkExperienceTab.jsx
  front-end/src/Views/CVEditorPage/functions/other.js
  front-end/src/Views/Steps/components/EditStep/EditStep.jsx
  front-end/src/components/VideoField/VideoField.jsx
  front-end/src/components/VideoField/VideoField.test.js
  front-end/src/components/VideoField/__snapshots__/VideoField.test.js.snap
  front-end/src/components/VideoField/components/ChangeVideo/ChangeVideo.jsx
  front-end/src/components/VideoField/components/ChangeVideo/ChangeVideo.test.js
  front-end/src/components/VideoField/components/ChangeVideo/__snapshots__/ChangeVideo.test.js.snap
  front-end/src/components/VideoField/components/ChangeVideo/index.js
  front-end/src/components/VideoField/components/index.js
  front-end/src/components/VideoField/functions/index.js
  front-end/src/components/VideoField/index.js
  front-end/src/components/index.js
  front-end/src/config/api.js
  front-end/src/constants/menuPositions.js
  front-end/src/constants/routes.js
  front-end/src/context/UserContext.js
  front-end/src/sass/components/_CVEditorTab.scss
  front-end/src/sass/components/_videoField.scss
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_CVEditorPage.scss
Labels: question

#203 Lazy loading
  front-end/src/Views/BlogPostForm/BlogpostForm.jsx
  front-end/src/Views/BlogPostForm/BlogpostFormContainer.jsx
  front-end/src/Views/BlogPostForm/index.js
  front-end/src/Views/CVCorrection/CVCorrection.jsx
  front-end/src/Views/CVCorrection/CVCorrection.test.js
  front-end/src/Views/CVCorrection/_components/CVRender/CVRender.jsx
  front-end/src/Views/CVCorrection/_components/index.js
Labels: enhancement

#211 navbar hover
  front-end/src/Views/Footer/Footer.jsx
  front-end/src/Views/Header/Header.jsx
  front-end/src/Views/Header/components/NotificationItemContainer.jsx
  front-end/src/Views/Header/components/NotificationToggle.jsx
  front-end/src/Views/Header/components/Notifications.jsx
  front-end/src/Views/PageHeader/components/NotificationToggle.jsx
  front-end/src/Views/PageHeader/components/Notifications.jsx
  front-end/src/sass/main.scss
  front-end/src/sass/pages/_footer.scss
  front-end/src/sass/pages/_header.scss
Labels: enhancement

#214 Mniejsze svg
  front-end/public/bell.svg
  front-end/public/left_tv.svg
  front-end/public/main.svg
  front-end/public/right_tv.svg
Labels: enhancement
